modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/glektarssza/minecraft-create-goggles-curio/master/forge-update.json"
displayURL = "https://github.com/glektarssza/minecraft-create-goggles-curio"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_author}"
description = '''${mod_description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "create"
mandatory = true
versionRange = "${create_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "curios"
mandatory = true
versionRange = "${curios_version_range}"
ordering = "NONE"
side = "BOTH"
