modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved."
[[mods]]
modId = "creategogglescurio"
version = "${file.jarVersion}"
displayName = "Create Goggles Curio"
displayURL = "https://github.com/glektarssza/minecraft-create-goggles-curio"
logoFile = "creategogglescurio_logo.png"
credits = ""
authors = "G'lek Tarssza"
description = '''
A mod for Minecraft 1.16.5 that adds the Create Goggles to the Curios head slot.
'''
[[dependencies.creategogglescurio]]
modId = "create"
mandatory = true
versionRange = "[v0.3.2g,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.creategogglescurio]]
modId = "curios"
mandatory = true
versionRange = "[1.16.5-4.0.5.3,)"
ordering = "NONE"
side = "BOTH"
