name: Push
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
      - id: download-dependencies
        name: Download dependencies
        run: |
          wget --quiet --directory-prefix=localMods https://mediafilez.forgecdn.net/files/3536/25/create-mc1.16.5_v0.3.2g.jar
      - id: build
        name: Build
        run: ./gradlew build
