name: Release
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
      - id: build
        name: Build
        run: ./gradlew build
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build/libs
          if-no-files-found: 'error'
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
      - id: download-artifacts
        name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: staging
      - id: attach-to-release
        name: Attach artifacts to release
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/upload-release-assets.js');
            await script({github, context, core}, ${{toJson(steps.download-artifacts.outputs.download-path)}});
